# Generated by Django 4.0.2 on 2022-02-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Por Asignar', 'Pendiente'), ('En mantenimiento', 'Mantenimiento'), ('En Proceso de Baja', 'Baja')], default='Activo', max_length=50),
        ),
        migrations.AddField(
            model_name='elemento',
            name='timestamps',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='elemento',
            name='tipoIngreso',
            field=models.CharField(choices=[('Donacion', 'Donacion'), ('Compra directa', 'Compra'), ('Comodato', 'Comodato'), ('Transferencia tecnológica', 'Transferencia'), ('Traspaso de otra Sede', 'Traspaso')], default='Compra directa', max_length=150),
        ),
        migrations.AddField(
            model_name='marca',
            name='timestamps',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='timestamps',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
