# Generated by Django 4.0.2 on 2022-03-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_elemento_estado_elemento_timestamps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='placa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
