# Generated by Django 4.0.3 on 2022-03-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_alter_elemento_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='esAsignado',
            field=models.BooleanField(default=False),
        ),
    ]
