# Generated by Django 4.0.3 on 2022-03-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_elemento_esasignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='enMantenimiento',
            field=models.BooleanField(default=False),
        ),
    ]
