# Generated by Django 4.0.3 on 2022-03-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_elemento_enmantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='enBaja',
            field=models.BooleanField(default=False),
        ),
    ]
