# Generated by Django 4.0.3 on 2022-03-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='irreparable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
