# Generated by Django 4.0.2 on 2022-02-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_elemento_estado_elemento_timestamps_and_more'),
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='timestamps',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deBaja', models.BooleanField(default=False)),
                ('descripcion', models.TextField(max_length=2000)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=50)),
                ('observaciones', models.TextField(max_length=2000)),
                ('estado', models.CharField(choices=[('En Proceso', 'Activo'), ('Irreparable', 'Irreparable'), ('En Proceso de Baja', 'Baja')], default='Activo', max_length=50)),
                ('timestamps', models.DateTimeField(auto_now=True)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.elemento')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
    ]
