# Generated by Django 4.0.3 on 2022-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_asignacion_timestamps_mantenimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='estado',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='enProceso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='irreparable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.TextField(max_length=20000000000),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='observaciones',
            field=models.TextField(max_length=20000000000),
        ),
    ]
