# Generated by Django 4.0.3 on 2022-03-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_remove_mantenimiento_estado_mantenimiento_enproceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='timestampsF',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
