# Generated by Django 4.0.3 on 2022-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_mantenimiento_timestampsf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='observaciones',
            field=models.TextField(blank=True, max_length=20000000000, null=True),
        ),
    ]
