# Generated by Django 4.0.2 on 2022-02-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificacion de Funcionario')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres del Funcionario')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos del Funcionario')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion de residencia')),
                ('telefono', models.CharField(max_length=100, verbose_name='Teléfono de Contacto')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('timestamps', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('NIT', models.IntegerField(primary_key=True, serialize=False, verbose_name='NIT/RUT de proveedor')),
                ('razonSocial', models.CharField(max_length=100, verbose_name='Nombre/Razón Social de Proveedor')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección de la empresa')),
                ('dir_venta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección de Punto de Venta (Si hubiere)')),
                ('telefono1', models.CharField(max_length=20, verbose_name='Telefono de Contacto')),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono de contacto Segundario (Si hubiere)')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electronico de contacto (Si hubiere)')),
                ('vendedor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre de contacto con la entidad/persona')),
                ('tel_vendedor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono de vendedor')),
                ('timestamps', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
