# Generated by Django 4.0.2 on 2022-02-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_remove_dependencia_sede'),
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='dependencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empresa.dependencia'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empresa.sede', verbose_name='Sede a la la que está adscrito'),
        ),
    ]
