# Generated by Django 4.0.2 on 2022-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_funcionario_dependencia_funcionario_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='identificacion',
            field=models.IntegerField(error_messages={'unique': 'Ya está registrado esta Identificación'}, primary_key=True, serialize=False, unique=True, verbose_name='Identificacion de Funcionario'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='NIT',
            field=models.IntegerField(error_messages={'unique': 'Ya está registrado esta identificacion'}, primary_key=True, serialize=False, unique=True, verbose_name='NIT/RUT de proveedor'),
        ),
    ]
