# Generated by Django 4.0.2 on 2022-03-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0004_alter_dependencia_dependencia_alter_sede_sede'),
        ('Personas', '0003_alter_funcionario_identificacion_alter_proveedor_nit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='dependencia',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empresa.sededependencia', verbose_name='Sede a la la que está adscrito'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='NIT',
            field=models.CharField(error_messages={'unique': 'Ya está registrado esta identificacion'}, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='NIT/RUT de proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='vendedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de contacto con la entidad/persona'),
        ),
    ]
