# Generated by Django 4.0.2 on 2022-02-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencia',
            name='sede',
        ),
    ]
