# Generated by Django 4.0.3 on 2022-03-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_remove_dependencia_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.dependencia')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresa.sede')),
            ],
            options={
                'verbose_name': 'SedeDependencia',
                'verbose_name_plural': 'SedeDependencias',
            },
        ),
    ]
