# Generated by Django 4.0.2 on 2022-03-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0003_sededependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='dependencia',
            field=models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre'}, max_length=50, unique=True, verbose_name='Ingrese nombre de la Dependencia'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='sede',
            field=models.CharField(error_messages={'unique': 'Ya existe un registro con este nombre'}, max_length=50, unique=True, verbose_name='Ingrese Nombre de la Sede'),
        ),
    ]
